### ISSUE TITLE
Trouble running on Heroku

### ISSUE THREAD

**Issue by abhiklodh** [ZumbaMaster313/Grocery#1]
The app isn't running on Heroku. Are there any specific instructions I have to follow to get the site running even locally?

**Comment by ZumbaMaster313** [comment]
@abhiklodh this app is still under early stages of development. I just started building less than a week ago.

**Comment by abhiklodh** [comment]
Any instructions on how to run the app on my computer?

**Comment by ZumbaMaster313** [comment]
@abhiklodh You have to download node.js https://nodejs.org/en/download/.
